config-version: 2

name: "brave_de_project"
version: "1.0.0"
require-dbt-version: ">=1.5.0"


profile: "brave_de_project" # Put your profile here

model-paths: ["brave_de_project/models"]
analysis-paths: ["brave_de_project/analyses"]
test-paths: ["brave_de_project/tests"]
seed-paths: ["brave_de_project/seeds"]
macro-paths: ["brave_de_project/macros"]
snapshot-paths: ["brave_de_project/snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  brave_de_project:
    +schema: raw

models:
  brave_de_project:
    database: BRAVE_DATABASE
    schema: DE_PROJECT
    raw_data:
      +materialized: view
    data_mart:
      +materialized: table
  +copy_grants: true

